server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          predicates:
            - Path=/api/v1/auth/**
          uri: lb://auth-service
        - id: member
          predicates:
            - Path=/api/v1/members/**
          uri: lb://member-service
        - id: event
          predicates:
            - Path=/api/v1/events/**
          uri: lb://event-service
        - id: order
          predicates:
            - Path=/api/v1/orders/**
          uri: lb://order-service

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false  # Ribbon을 사용하지 않도록 설정
      round-robin:
        enabled: true  # Round Robin을 사용하도록 설정

eureka:
  client:
    service-url.defaultZone: http://192.168.139.100:8761/eureka

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, refresh, routes
  endpoint:
    prometheus:
      enabled: true
