server:
  port: 8081

spring:
  application:
    name: member-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://member-service-database:5432/member_domain
    username: jeein
    password: 93671665
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        highlight_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.139.100:8761/eureka/
  instance:
    ip-address: 192.168.136.97  # 서비스의 IP 주소를 수동으로 지정
    hostname: 192.168.136.97
    prefer-ip-address: true  # IP 주소로 등록

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, refresh
  endpoint:
    prometheus:
      enabled: true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
    disable-swagger-default-url: false
    display-request-duration: true
