server:
  port: 8081

spring:
  application:
    name: member-service-dev

eureka:
  client:
    service-url:
      defaultZone: http://192.168.139.100:8761/eureka/

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, refresh
  endpoint:
    prometheus:
      enabled: true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
    disable-swagger-default-url: false
    display-request-duration: true
